version: '3.8'

services:
  gpu_database:
    image: postgres:15.3
    container_name: nvidia_postgres
    environment:
      POSTGRES_USER: Rick
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: gpu_db
    ports:
      - "6000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gpu_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com #Change this line with some other email which is convinient to you
      PGADMIN_DEFAULT_PASSWORD: your_password_here
    ports:
      - "8080:80"
    networks:
      - gpu_network
    depends_on:
      - gpu_database
volumes:
  pgdata:

networks:
  gpu_network:
    driver: bridge
